before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: c+sKfIVHwPnZMFq1wMAzG6HYwneR9qHdHdf77RPN6CIfdAHq7e1jjkvRz3teCIEnJFVh+cc1Cp+csoqMGy/SvenoEkHXktXTsGw3ZOKQ6ESOmd0JvqQnE16VdDX8s0j1uxZAwKQ8ZsVXDfFjaTMm2FTsenjoXcjvW8Jbho0OF+zXg/FJfewupNEkCANuyRTFkyNAE5mk7SeJgLkV5AwZtDinkKTRK2HiaoG02cNXVCpJ39nx1JqTNeYUD7EK6h7LFNTTbsEk5YnSwMVQWL/GTRuPkolA/4J6Z/o/jbZXm++SpnTWeCyDOVe138jPQQ8OievNf1bR/lFqaabEVEgvlPLMRsZ6e0d2fJvgkeqMh4iAgQl3xz5vcfK6MglssQ5J2D1mkK3tSHK5e3wRQqkkxEtbupgAVVWBfSNul4dK/RivAYonbb15U71OC4uSs+No/IZzCwfjpqluzRxs+8FFjbfytMy4de27DJGWJGYaT1OH6XrXaBmuFGrx+2spyijRjxE+VbaWu7I5hAbURxlp1xwREaE9Rn4TB4z8ow0zflNKi4Y5v1ytXW8sKT8EPSKevlVBFyY4iP4RxB9IvfqDiN2Q42beMS5E/7arBIL6+I+yFVXUuHF3UGwSeYXQwV2qJBYnlcLJPVrIRIXBFCnhbNwlsKe6ylRGECEIolqohfA= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    # - 6
    - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
